apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logvol
  namespace: demo-pvc
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 1Gi